# This plugin was created by the Undefined Team
# Its a lite weight and easy to use Combat Log plugin
# All the settings can be changed in the admin GUI in game using /admincombat
# This plugin is under the MIT LICENCE
# Any question or help join the discord here : https://discord.gg/udq9r4kves


# Combat settings
settings:

  # How long the combat timer should be in seconds.
  timer: 10

  # If a player with the 'undefined.combat.bypass' permission
  bypass: true

  # If a bossbar used be used to display a tag
  bossbar: true

  # If an action bar used be used to display a tag
  actionbar: true

  # If a player should be killed when leaving the server when in combat
  kill-on-quit: true

# Blocked settings
blocked:
  # If an elytra is allowed to be used in combat
  elytra: true

  # If a trident with riptide is allowed in combat
  riptide: true

  # If ender pearls are allowed to be used in combat
  ender-pearls: true

  commands:
    - "msg"


